### ISSUE TITLE
cannot install on laravel version 5.2.39

### ISSUE THREAD

**Issue by ronnievisser** [yurykabanov/laravel-postgres-ext#1]
Hi,

A composer require yurykabanov/laravel-postgres-ext causes the package to fail installation:

Problem 1
    - Installation request for laravel/laravel No version set (parsed as 1.0.0) -> satisfiable by laravel/laravel[No version set (parsed as 1.0.0)].
    - yurykabanov/laravel-postgres-ext v0.1 requires laravel/laravel ^5.2 -> satisfiable by laravel/laravel[v5.2.0, v5.2.15, v5.2.23, v5.2.24, v5.2.27, v5.2.29, v5.2.31].
    - Can only install one of: laravel/laravel[v5.2.0, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.15, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.23, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.24, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.27, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.29, No version set (parsed as 1.0.0)].
    - Can only install one of: laravel/laravel[v5.2.31, No version set (parsed as 1.0.0)].
    - Installation request for yurykabanov/laravel-postgres-ext ^0.1.0 -> satisfiable by yurykabanov/laravel-postgres-ext[v0.1].

**Comment by yurykabanov** [comment]
Hi, @RonnieVisser 

Yeah, I messed up with laravel dependency (required **laravel/laravel** instead of **laravel/framework**) and then forgot to bump package version. I've pushed new tag, so it's fixed now.

**Comment by ronnievisser** [comment]
Cool, working now!

thanks
