### ISSUE TITLE
 Syntax error: 7 ERROR:  syntax error at or near "on"

### ISSUE THREAD

**Issue by ronnievisser** [yurykabanov/laravel-postgres-ext#2]
Hi,

I'm getting following erro when running a query with upsert method.

Next Illuminate\Database\QueryException: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "on"
LINE 1: ...$25, $26, $27, $28, $29, $30, $31, $32, $33, $34) on conflic...
#3 /home/vagrant/Code/PHP/data/vendor/yurykabanov/laravel-postgres-ext/src/Query/Builder.php(35): Illuminate\Database\Connection->insert('insert into "ag...', Array)

**Comment by ronnievisser** [comment]
probably because im running 9.4.6.

**Comment by yurykabanov** [comment]
Yeah, you're right, **UPSERT** was introduced in PostgreSQL 9.5
